### PR TITLE
comment out noisy deprecation warnings temporarily to reduce log volume

### PR DESCRIPTION
**Pull request by bderusha**

### CODE REVIEW

**Comment by bderusha** [comment]
@robrap moved to docstring/comment as appropriate

**Comment by robrap** [comment]
@jmbowman: As a follow-up, what is the right way to add internal deprecation warnings that show up in our deprecation report, but don't muddy up the logs for Production?

**Comment by jmbowman** [comment]
We actually did work for the Django 1.11 upgrade specifically to show deprecation warnings in the production logs, to catch anything that the test suite may have missed: https://github.com/edx/edx-platform/pull/17323 .  We should be able to [adjust the filter](https://docs.python.org/3.5/library/warnings.html#the-warnings-filter) to exclude particularly verbose warnings, or perhaps add a toggle to only log these warnings when we're actively working on an upgrade that needs to collect them.

**Comment by robrap** [comment]
@jmbowman: I'd vote:
1. Disable deprecation logging from Prod while we aren't actually looking at it, followed by:
2. Adjust the filter when and if we enable in Prod and a particular warning is too verbose.

**Pull request merged**
