### PR TITLE
SE-3724: squashes warnings related to edx_django_utils usage

### PR DESCRIPTION
**Pull request by eLRuLL**
This PR squashes warnings related to the usage of the [edx_django_utils](https://github.com/edx/edx-django-utils) package (as part of the [Squash a Warning event](https://discuss.openedx.org/t/squash-a-warning-earn-a-badge/3497)):

Reduced warnings from 46 to 19

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @eLRuLL! I've created [OSPR-5302](https://openedx.atlassian.net/browse/OSPR-5302) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nasthagiri** [comment]
@robrap Can you take a look at this?

**Comment by robrap** [comment]
Thank you @eLRuLL. Do you want to bump the version to 5.2.2 so the update can be released?

**Review by robrap — COMMENTED** [review]
I don't think I added my earlier comment as a review comment.
Thanks again @eLRuLL.  Looks good.  Bumping the version to 5.2.2 would enable this update to be released.

**Comment by eLRuLL** [comment]
> I don't think I added my earlier comment as a review comment.
> Thanks again @eLRuLL. Looks good. Bumping the version to 5.2.2 would enable this update to be released.

oh that's great, bumped :+1:

**Comment by edx-webhook** [comment]
@eLRuLL 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-rest-api-client&entry.867055334=https://github.com/edx/edx-rest-api-client/pull/114&entry.1484655318=https://github.com/eLRuLL&entry.752974735=2020-12-14+00:29&entry.1917517419=2020-12-14+22:38&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by robrap** [comment]
👍

**Pull request merged**
