### PR TITLE
Allow passing a presupplied JWT for API client authorization.

### PR DESCRIPTION
**Pull request by peter-fogg**
This will be used by the async fulfillment work.

@renzo @clintonb @bderusha @rock345

### CODE REVIEW

**Comment by clintonb** [comment]
Why is this necessary? If the service can create a JWT, it has the necessary information—signing key, username—to let the client create the JWT.

**Comment by peter-fogg** [comment]
@clintonb The service could create its own JWT, I suppose. This seemed a bit cleaner, since then generation of the JWT can be centralized in the ecommerce service instead of being pushed out to the worker. I'll take a look at having the worker do it.

**Comment by clintonb** [comment]
You run into potential expiration issues if you have Otto push the token to the user. Say it takes 30 minutes for the worker to get to the task. By that time the JWT will have expired.

**Comment by clintonb** [comment]
If doing OAuth 2.0 + refresh tokens is too taxing, I'm willing to fallback to having the workers know about the Otto's signing key; however, it would be ideal if we had a mechanism of assigning a key to a specific user (similar to OAuth 2.0).

**Comment by jimabramson** [comment]
reopening this - it accomplishes what we're trying to do in #15

**Comment by jimabramson** [comment]
@peter-fogg @clintonb @zubair-arbi @rlucioni rebased and updated this PR.

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
:+1:

**Comment by peter-fogg** [comment]
:ship:

**Comment by bderusha** [comment]
:+1:

**Comment by jimabramson** [comment]
@zubair-arbi #15 can be closed at this point.

**Pull request merged**
